<?php

namespace CWM\BroadWorksConnector\Ocip\Models;

/**
 * MediaStream
 *
 * Media Stream Type.  Subscriber's media is sent separately from the media generated by the called/calling parties when "Dual" is selected while "Single" is a single media stream that contains all media.
 *
 * @method static MediaStream DUAL()
 * @method static MediaStream SINGLE()
 * @EnumValueType string
 */
class MediaStream extends \MyCLabs\Enum\Enum
{
    public const DUAL = 'Dual';

    public const SINGLE = 'Single';
}

